# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tickcats < Formula
  desc "Keyboard-first local kanban board for solo developers"
  homepage "https://github.com/dawidsok/tickcats"
  version "0.1.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dawidsok/tickcats/releases/download/v0.1.4/tickcats_0.1.4_darwin_amd64.tar.gz"
      sha256 "fa0cd68be1b26ebdf417a3caead49aa1eed2e56e7468447c4f16612a1a1491f8"

      define_method(:install) do
        bin.install "tickcats"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dawidsok/tickcats/releases/download/v0.1.4/tickcats_0.1.4_darwin_arm64.tar.gz"
      sha256 "4d8880bb9c21065c025411ba8f63a68235956e82e83195063076cfae9b7e46b8"

      define_method(:install) do
        bin.install "tickcats"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dawidsok/tickcats/releases/download/v0.1.4/tickcats_0.1.4_linux_amd64.tar.gz"
      sha256 "4feaf9c08651f69308fc4a6a19c499e12eef68aaec2db6456843ade673778b55"
      define_method(:install) do
        bin.install "tickcats"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dawidsok/tickcats/releases/download/v0.1.4/tickcats_0.1.4_linux_arm64.tar.gz"
      sha256 "b4d8dc93b8a92a8fa433ca1ecbcee50098713c5a656d7effb7bdd199c7bb248e"
      define_method(:install) do
        bin.install "tickcats"
      end
    end
  end

  test do
    system "#{bin}/tickcats", "--path", "#{testpath}/.tickcats", "init"
    assert_predicate testpath/".tickcats/backlog", :directory?
  end
end
